Ass Blast Usa
MisterBones2910/Merchan-TG-uild pull request #45
Opened 2021-07-22 19:45 UTC by karmaisblackandbluepilled

Adds farting, butts, buttflowers, buttshoes, fartium, Bible gibbing.
There's currently two issues, the fart emote happens twice due to a fix that TCEO gave me and the butt getting blasted off creates a runtime due to a signal? I think. I don't know how to fix these issues.

2021-07-22 21:14 UTC, TheChosenEvilOne commented on code/modules/mob/living/carbon/emote.dm
> +		..()
```suggestion
```

2021-07-22 21:32 UTC, TheChosenEvilOne commented on code/modules/mob/living/carbon/emote.dm
> +							new_dir = 4
```suggestion
					var/new_dir = REVERSE_DIR(user.dir)
```

2021-07-22 21:34 UTC, TheChosenEvilOne commented on code/datums/keybinding/emote.dm
> +	description = "Uh oh, stinky!"
```suggestion
```
these are not needed AFAIK

2021-07-22 22:36 UTC, TheChosenEvilOne commented on code/modules/surgery/organs/ass.dm
> +/obj/item/organ/butt/attackby(var/obj/item/W, mob/user as mob, params) // copypasting bot manufucturing process, im a lazy fuck
```suggestion
/obj/item/organ/butt/attackby(obj/item/W, mob/living/user, params) // copypasting bot manufucturing process, im a lazy fuck
```
linter complaining about this, also I don't see a reason for the `mob/user as mob` so

2021-07-23 15:07 UTC, TheChosenEvilOne commented on code/_onclick/click.dm
> +				if(target in carbon_src.bodyparts || target in carbon_src.internal_organs)
linter screaming about this one
```suggestion
				if((target in carbon_src.bodyparts) || (target in carbon_src.internal_organs))
```

2021-07-23 21:53 UTC, karmaisblackandbluepilled commented
don't merge this

2021-07-23 21:53 UTC, karmaisblackandbluepilled commented
something here makes bags unusable which isn't that good

2021-07-23 22:36 UTC, karmaisblackandbluepilled commented
ok i fixed it time to uhh got dam pussy fart shit nREDACTED push it

2021-07-23 22:42 UTC, TheChosenEvilOne requested changes
Alright, I don't really see anything wrong other than some minor style issues after these which can be ignored.

2021-07-23 22:42 UTC, TheChosenEvilOne commented on code/modules/surgery/organs/ass.dm
> +	if(!getorganslot("butt"))
```suggestion
	if(!getorganslot(ORGAN_SLOT_BUTT))
```

2021-07-23 22:42 UTC, TheChosenEvilOne commented on code/modules/surgery/organs/organ_internal.dm
> +		if(!getorganslot("butt"))
```suggestion
		if(!getorganslot(ORGAN_SLOT_BUTT))
```

2021-07-23 22:42 UTC, TheChosenEvilOne commented on code/modules/reagents/chemistry/reagents/drug_reagents.dm
> +			if(B)
```suggestion
		if(prob(7))
			if(H.getorganslot(ORGAN_SLOT_BUTT))
```

2021-07-23 22:49 UTC, TheChosenEvilOne approved these changes

2021-07-23 22:55 UTC, TheChosenEvilOne commented
alright, I don't see anything that horribly wrong.

2021-07-23 22:55 UTC, merged