Watch these cool prs
MisterBones2910/Merchan-TG-uild pull request #47
Opened 2021-07-24 13:32 UTC by xNightHowlx

## About The Pull Request

1) Makes emotes only log if performed by players, so no more 5 terrabyte logs because "Monkey (281) gasped!x20"
2) Allows turrets to be accessed 1 tile away, and can now be alt-clicked to unlock/lock.
3) Health Analyzers now show the severity of a bleed.

## Why It's Good For The Game

1) Smaller logs, easier to read and comprehend, meaning swifter punishments and faster and more precise conclusions
2) Ease of use
3) More depth to health alanyzers

## Changelog
:cl:
add: Health Analyzers now show severity of a bleed.
qol: Turrets can now be accessed 1 tile away, and can be locked/unlocked with alt-click
admin: Emotes are only logged if performed by players.
/:cl:

2021-07-24 13:35 UTC, karmaisblackandbluepilled commented
i'm curious, are these gripes you've had with tg, you tried to pr to fix them there and they didn't accept them?

2021-07-24 13:40 UTC, TheChosenEvilOne commented on code/game/machinery/porta_turret/portable_turret.dm
> +			/obj/machinery/turretid/proc/togglelock(mob/user)
I got confused here for a second but it was the indentation being weird
```suggestion
/obj/machinery/turretid/proc/togglelock(mob/user)
```

2021-07-24 13:44 UTC, TheChosenEvilOne commented on code/game/objects/items/devices/scanners.dm
> +	if(ishuman(M) || istype(M,/mob/living/carbon/monkey)) // Monkey organs can also be shown now
might as well make this a iscarbon check instead.
```suggestion
	if(iscarbon(M))
```

2021-07-24 13:51 UTC, xNightHowlx commented
> i'm curious, are these gripes you've had with tg, you tried to pr to fix them there and they didn't accept them?

Haven't PR'd it to TG :trollface:

2021-07-24 14:28 UTC, TheChosenEvilOne commented
```
code/game/machinery/porta_turret/portable_turret.dm:945:error: stat: undefined var
code/game/objects/items/devices/scanners.dm:405:error: H.bleed_rate: undefined var
code/game/objects/items/devices/scanners.dm:407:error: H.bleed_rate: undefined var
code/game/objects/items/devices/scanners.dm:409:error: H.bleed_rate: undefined var
code/game/objects/items/devices/scanners.dm:411:error: H.bleed_rate: undefined var
code/game/objects/items/devices/scanners.dm:413:error: H.bleed_rate: undefined var
code/game/objects/items/devices/scanners.dm:415:error: H.bleed_rate: undefined var
code/game/objects/items/devices/scanners.dm:418:error: H.bleedsuppress: undefined var
```

2021-07-24 14:34 UTC, TheChosenEvilOne requested changes

2021-07-24 14:34 UTC, TheChosenEvilOne commented on code/game/machinery/porta_turret/portable_turret.dm
> +	if(stat & BROKEN)
```suggestion
	if(machine_stat & BROKEN)
```

2021-07-24 14:34 UTC, TheChosenEvilOne commented on code/game/objects/items/devices/scanners.dm
> +						bleedtext = "Extreme!"
```suggestion
					var/bleed_rate = H.get_total_bleed_rate()
					if(bleed_rate <= 5)
						bleedtext = "Negligible"
					else if(bleed_rate <= 10)
						bleedtext = "Minor"
					else if(bleed_rate <= 15)
						bleedtext = "Moderate"
					else if(bleed_rate <= 20)
						bleedtext = "Serious"
					else if(bleed_rate <= 30)
						bleedtext = "Critical!"
					else if(bleed_rate > 30)
						bleedtext = "Extreme!"
```

2021-07-24 14:34 UTC, TheChosenEvilOne commented on code/game/objects/items/devices/scanners.dm
> +						bandagetext = "Bandaged"
as of right now I don't really see how to implement this proper without going through all limbs
```suggestion
```

2021-07-24 14:34 UTC, TheChosenEvilOne commented on code/game/objects/items/devices/scanners.dm
> +					render_list += "<span class='alert ml-1'><b>Subject is bleeding! [bleedtext ? "([bleedtext])" : ""][bandagetext ? "(Bandaged)" : ""]</b></span>\n"
```suggestion
					render_list += "<span class='alert ml-1'><b>Subject is bleeding! [bleedtext ? "([bleedtext])" : ""]</b></span>\n"
```

2021-07-24 14:57 UTC, TheChosenEvilOne commented on code/game/objects/items/devices/scanners.dm
> +						bleedtext = "Extreme!"
honestly this should just be a switch

2021-07-27 16:10 UTC, TheChosenEvilOne commented on code/game/objects/items/devices/scanners.dm
> +						bleedtext = "Extreme!"
again, this should be a switch.

2021-08-25 19:07 UTC, closed without merging